TaskManager/main/cal/urls.py
from django.urls import path
from . import views
from members.views import signin

urlpatterns = [
    path('signin/',signin, name = 'signin'),
    path('calendar-data/', views.calendar_data, name='calendar_data'),
    path('', views.calendar, name='calendar'),
]

TaskManager/main/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from members.views import signup
from members.views import signin
from members.views import signout
from cal.views import calendar
from tasks.views import new, delete

urlpatterns = [
    path('', views.home, name = 'home'),
    path("admin/", admin.site.urls),
    path("home/", views.dashboard, name = 'dashboard'),
    path("members/", views.members, name='members'),
    path("newuser/", signup, name='newuser'),
    path("currentuser/", signin, name='currentuser'),
    path("logout/", signout, name = 'logout'),
    path("tasks/", include('tasks.urls')),
    path("achievements/", include('achievements.urls')),
    path('calendar/', include('cal.urls'))
]

TaskManager/main/tasks/urls.py
from django.urls import path
from . import views
from members.views import signin

app_name = 'tasks' 

urlpatterns = [
    path('', views.tasks, name='index'),
    path('new/', views.new, name='new'),
    path('signin/',signin, name = 'signin'),
    path('complete/<int:task_id>/', views.complete, name='complete'), 
    path('delete/<int:task_id>/', views.delete, name='delete')
]

TaskManager/main/main/views.py
from django.shortcuts import render

from django.http import HttpResponse
from django.template import loader
from members.models import Member
from tasks.models import Task
from achievements.models import Achievement
from cal.models import CalendarDate
from django.contrib.auth.decorators import login_required


def home(request):
    task_count = 0

    if request.user.is_authenticated:
        task_count = Task.objects.filter(
            user=request.user,
            completed=False
        ).count()
    task_list = []
    task_list_completed = []
    if request.user.is_authenticated:
       task_list = Task.objects.filter(
          user=request.user,
          completed=False
       )
    if request.user.is_authenticated:
       task_list_completed = Task.objects.filter(
          user=request.user,
          completed=True
       )
  
    return render(request, 'home.html', {
        'task_count': task_count,
        'task_list': task_list,
        'task_list_completed': task_list_completed,
    }) 

def dashboard(request):
    return render(request, 'home.html') 

def members(request):
  mymembers = Member.objects.all().values()
  template = loader.get_template('all_members.html')
  context = {
    'mymembers': mymembers,
  }
  return HttpResponse(template.render(context, request))

@login_required(login_url="/currentuser")
def tasks(request):
  mytasks = Task.objects.filter(user=request.user)
  template = loader.get_template('all_tasks.html')
  context = {
    'mytasks': mytasks,
  }
  return HttpResponse(template.render(context, request))

def achievements(request):
  myachievements = Achievement.objects.all().values()
  template = loader.get_template('all_achievements.html')
  context = {
    'myachievements': myachievements,
  }
  return HttpResponse(template.render(context, request))

@login_required
def calendar(request):
    return render(request, 'calendar.html')

TaskManager/main/main/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width-device-width, intial-scale=1, maximum-scale=1"/> 
  <link rel='stylesheet' type="text/css" href="https://bootswatch.com/5/sandstone/bootstrap.min.css">
</head>
<body>
    <div class="topnav">
        <a class="{% if request.path == '/' %}active{% endif %}" href="{% url 'home' %}">Home</a>
        <a class="{% if request.path == '/tasks/' %}active{% endif %}" href="{% url 'tasks:index' %}">Tasks</a>
        <a class="{% if request.path == '/calendar/' %}active{% endif %}" href="{% url 'calendar' %}">Calendar</a>
        <a class="{% if request.path == '/achievements/' %}active{% endif %}" href="{% url 'achievements' %}">Achievements</a>
        <a class="{% if request.path == '/currentuser/' %}active{% endif %}" href="{% url 'currentuser' %}">Sign In</a>
        <a class="{% if request.path == '/newuser/' %}active{% endif %}" href="{% url 'newuser' %}">Sign Up</a>
    </div>
<style>
.topnav {
  background-color: rgb(158, 76, 251);
  overflow: hidden;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 10px 105.65px;
  text-decoration: none;
  font-size: 20px;
}

.topnav a:hover {
  background-color: #b7b4b4;
  color: black;
}

.topnav a.active {
  background-color: rgb(184, 121, 92);
  color: white;
}

.footer-bar {
  background-color: #9e4cfb;
  color: white;
  text-align: center;
  padding: 10px;
  position: fixed;
  bottom: 0;
  left: 0;
  width: 100%;
  z-index: 1000;
}

body {
      padding-bottom: 50px;
    }

</style>

{% block content %}
{% endblock %}

<div class="footer-bar">

</div>

</body>
</html>